sonar.projectKey=octa1124_femsolver
sonar.organization=octa1124
sonar.projectName=femsolver
sonar.projectVersion=0.1.0

sonar.sources=src,include,tools
sonar.tests=tests
sonar.exclusions=build/**,generated/**,results/**,docker/**
sonar.test.inclusions=tests/**
sonar.python.version=3.11
sonar.cfamily.compile-commands=build/gcc-debug/compile_commands.json
